name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test --if-present # Adicione seus testes aqui

  build-and-deploy:
    needs: test # Garante que os testes passem antes do deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Secret do GitHub
        password: ${{ secrets.DOCKER_PASSWORD }} # Secret do GitHub
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Contexto do build (raiz do projeto)
        push: true # Publica a imagem
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/trabalho-ravach-nodejs:latest
          ${{ secrets.DOCKER_USERNAME }}/trabalho-ravach-nodejs:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max